[package]
name = "feather-api-ffi"
version = "0.2.0"
authors = ["Amber Kowalski <amberkowalski03@gmail.com>"]
edition = "2018"

[features]
default = []
wasm = ["wasmer"]

[dependencies]
wasmer = { version = "1.0.0-alpha3", optional = true }