[package]
name = "feather-api-ffi"
version = "0.1.0"
authors = ["Amber Kowalski <amberkowalski03@gmail.com>"]
edition = "2018"

[features]
default = []
wasm = ["wasmer-runtime"]

[dependencies]
wasmer-runtime = { version = "0.17.1", optional = true }